"""foxai TTS 技能包。"""
from .tts_client import (
    TTSClient,
    TTSConfig,
    OutputTarget,
    VOICE_GROUPS,
    VALID_VOICES,
    TTSError,
    TTSAuthError,
    TTSBadRequest,
    TTSServerError,
    TTSEmptyAudio,
    TTSNetworkError,
    # 批量类型
    BatchItem,
    BatchItemResult,
    BatchConfig,
    BatchReport,
    DEFAULT_BASE_URL,
    DEFAULT_API_KEY,
    DEFAULT_VOICE,
    main,
)

__all__ = [
    "TTSClient",
    "TTSConfig",
    "OutputTarget",
    "VOICE_GROUPS",
    "VALID_VOICES",
    "TTSError",
    "TTSAuthError",
    "TTSBadRequest",
    "TTSServerError",
    "TTSEmptyAudio",
    "TTSNetworkError",
    "BatchItem",
    "BatchItemResult",
    "BatchConfig",
    "BatchReport",
    "DEFAULT_BASE_URL",
    "DEFAULT_API_KEY",
    "DEFAULT_VOICE",
    "main",
]